package com.tky.mqtt.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.tky.mqtt.dao.Messages;
import com.tky.mqtt.dao.ParentDept;
import com.tky.mqtt.dao.SubDept;
import com.tky.mqtt.dao.TopContacts;
import com.tky.mqtt.dao.ChatList;

import com.tky.mqtt.dao.MessagesDao;
import com.tky.mqtt.dao.ParentDeptDao;
import com.tky.mqtt.dao.SubDeptDao;
import com.tky.mqtt.dao.TopContactsDao;
import com.tky.mqtt.dao.ChatListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messagesDaoConfig;
    private final DaoConfig parentDeptDaoConfig;
    private final DaoConfig subDeptDaoConfig;
    private final DaoConfig topContactsDaoConfig;
    private final DaoConfig chatListDaoConfig;

    private final MessagesDao messagesDao;
    private final ParentDeptDao parentDeptDao;
    private final SubDeptDao subDeptDao;
    private final TopContactsDao topContactsDao;
    private final ChatListDao chatListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messagesDaoConfig = daoConfigMap.get(MessagesDao.class).clone();
        messagesDaoConfig.initIdentityScope(type);

        parentDeptDaoConfig = daoConfigMap.get(ParentDeptDao.class).clone();
        parentDeptDaoConfig.initIdentityScope(type);

        subDeptDaoConfig = daoConfigMap.get(SubDeptDao.class).clone();
        subDeptDaoConfig.initIdentityScope(type);

        topContactsDaoConfig = daoConfigMap.get(TopContactsDao.class).clone();
        topContactsDaoConfig.initIdentityScope(type);

        chatListDaoConfig = daoConfigMap.get(ChatListDao.class).clone();
        chatListDaoConfig.initIdentityScope(type);

        messagesDao = new MessagesDao(messagesDaoConfig, this);
        parentDeptDao = new ParentDeptDao(parentDeptDaoConfig, this);
        subDeptDao = new SubDeptDao(subDeptDaoConfig, this);
        topContactsDao = new TopContactsDao(topContactsDaoConfig, this);
        chatListDao = new ChatListDao(chatListDaoConfig, this);

        registerDao(Messages.class, messagesDao);
        registerDao(ParentDept.class, parentDeptDao);
        registerDao(SubDept.class, subDeptDao);
        registerDao(TopContacts.class, topContactsDao);
        registerDao(ChatList.class, chatListDao);
    }
    
    public void clear() {
        messagesDaoConfig.getIdentityScope().clear();
        parentDeptDaoConfig.getIdentityScope().clear();
        subDeptDaoConfig.getIdentityScope().clear();
        topContactsDaoConfig.getIdentityScope().clear();
        chatListDaoConfig.getIdentityScope().clear();
    }

    public MessagesDao getMessagesDao() {
        return messagesDao;
    }

    public ParentDeptDao getParentDeptDao() {
        return parentDeptDao;
    }

    public SubDeptDao getSubDeptDao() {
        return subDeptDao;
    }

    public TopContactsDao getTopContactsDao() {
        return topContactsDao;
    }

    public ChatListDao getChatListDao() {
        return chatListDao;
    }

}
