package com.tky.mqtt.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.tky.mqtt.dao.Messages;
import com.tky.mqtt.dao.ParentDept;
import com.tky.mqtt.dao.SubDept;
import com.tky.mqtt.dao.TopContacts;
import com.tky.mqtt.dao.ChatList;
import com.tky.mqtt.dao.GroupChats;
import com.tky.mqtt.dao.SelectedId;
import com.tky.mqtt.dao.SystemMsg;
import com.tky.mqtt.dao.MsgHistory;
import com.tky.mqtt.dao.LocalPhone;
import com.tky.mqtt.dao.NotifyList;
import com.tky.mqtt.dao.FilePicture;
import com.tky.mqtt.dao.ModuleCount;
import com.tky.mqtt.dao.SlowNotifyList;

import com.tky.mqtt.dao.MessagesDao;
import com.tky.mqtt.dao.ParentDeptDao;
import com.tky.mqtt.dao.SubDeptDao;
import com.tky.mqtt.dao.TopContactsDao;
import com.tky.mqtt.dao.ChatListDao;
import com.tky.mqtt.dao.GroupChatsDao;
import com.tky.mqtt.dao.SelectedIdDao;
import com.tky.mqtt.dao.SystemMsgDao;
import com.tky.mqtt.dao.MsgHistoryDao;
import com.tky.mqtt.dao.LocalPhoneDao;
import com.tky.mqtt.dao.NotifyListDao;
import com.tky.mqtt.dao.FilePictureDao;
import com.tky.mqtt.dao.ModuleCountDao;
import com.tky.mqtt.dao.SlowNotifyListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messagesDaoConfig;
    private final DaoConfig parentDeptDaoConfig;
    private final DaoConfig subDeptDaoConfig;
    private final DaoConfig topContactsDaoConfig;
    private final DaoConfig chatListDaoConfig;
    private final DaoConfig groupChatsDaoConfig;
    private final DaoConfig selectedIdDaoConfig;
    private final DaoConfig systemMsgDaoConfig;
    private final DaoConfig msgHistoryDaoConfig;
    private final DaoConfig localPhoneDaoConfig;
    private final DaoConfig notifyListDaoConfig;
    private final DaoConfig filePictureDaoConfig;
    private final DaoConfig moduleCountDaoConfig;
    private final DaoConfig slowNotifyListDaoConfig;

    private final MessagesDao messagesDao;
    private final ParentDeptDao parentDeptDao;
    private final SubDeptDao subDeptDao;
    private final TopContactsDao topContactsDao;
    private final ChatListDao chatListDao;
    private final GroupChatsDao groupChatsDao;
    private final SelectedIdDao selectedIdDao;
    private final SystemMsgDao systemMsgDao;
    private final MsgHistoryDao msgHistoryDao;
    private final LocalPhoneDao localPhoneDao;
    private final NotifyListDao notifyListDao;
    private final FilePictureDao filePictureDao;
    private final ModuleCountDao moduleCountDao;
    private final SlowNotifyListDao slowNotifyListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messagesDaoConfig = daoConfigMap.get(MessagesDao.class).clone();
        messagesDaoConfig.initIdentityScope(type);

        parentDeptDaoConfig = daoConfigMap.get(ParentDeptDao.class).clone();
        parentDeptDaoConfig.initIdentityScope(type);

        subDeptDaoConfig = daoConfigMap.get(SubDeptDao.class).clone();
        subDeptDaoConfig.initIdentityScope(type);

        topContactsDaoConfig = daoConfigMap.get(TopContactsDao.class).clone();
        topContactsDaoConfig.initIdentityScope(type);

        chatListDaoConfig = daoConfigMap.get(ChatListDao.class).clone();
        chatListDaoConfig.initIdentityScope(type);

        groupChatsDaoConfig = daoConfigMap.get(GroupChatsDao.class).clone();
        groupChatsDaoConfig.initIdentityScope(type);

        selectedIdDaoConfig = daoConfigMap.get(SelectedIdDao.class).clone();
        selectedIdDaoConfig.initIdentityScope(type);

        systemMsgDaoConfig = daoConfigMap.get(SystemMsgDao.class).clone();
        systemMsgDaoConfig.initIdentityScope(type);

        msgHistoryDaoConfig = daoConfigMap.get(MsgHistoryDao.class).clone();
        msgHistoryDaoConfig.initIdentityScope(type);

        localPhoneDaoConfig = daoConfigMap.get(LocalPhoneDao.class).clone();
        localPhoneDaoConfig.initIdentityScope(type);

        notifyListDaoConfig = daoConfigMap.get(NotifyListDao.class).clone();
        notifyListDaoConfig.initIdentityScope(type);

        filePictureDaoConfig = daoConfigMap.get(FilePictureDao.class).clone();
        filePictureDaoConfig.initIdentityScope(type);

        moduleCountDaoConfig = daoConfigMap.get(ModuleCountDao.class).clone();
        moduleCountDaoConfig.initIdentityScope(type);

        slowNotifyListDaoConfig = daoConfigMap.get(SlowNotifyListDao.class).clone();
        slowNotifyListDaoConfig.initIdentityScope(type);

        messagesDao = new MessagesDao(messagesDaoConfig, this);
        parentDeptDao = new ParentDeptDao(parentDeptDaoConfig, this);
        subDeptDao = new SubDeptDao(subDeptDaoConfig, this);
        topContactsDao = new TopContactsDao(topContactsDaoConfig, this);
        chatListDao = new ChatListDao(chatListDaoConfig, this);
        groupChatsDao = new GroupChatsDao(groupChatsDaoConfig, this);
        selectedIdDao = new SelectedIdDao(selectedIdDaoConfig, this);
        systemMsgDao = new SystemMsgDao(systemMsgDaoConfig, this);
        msgHistoryDao = new MsgHistoryDao(msgHistoryDaoConfig, this);
        localPhoneDao = new LocalPhoneDao(localPhoneDaoConfig, this);
        notifyListDao = new NotifyListDao(notifyListDaoConfig, this);
        filePictureDao = new FilePictureDao(filePictureDaoConfig, this);
        moduleCountDao = new ModuleCountDao(moduleCountDaoConfig, this);
        slowNotifyListDao = new SlowNotifyListDao(slowNotifyListDaoConfig, this);

        registerDao(Messages.class, messagesDao);
        registerDao(ParentDept.class, parentDeptDao);
        registerDao(SubDept.class, subDeptDao);
        registerDao(TopContacts.class, topContactsDao);
        registerDao(ChatList.class, chatListDao);
        registerDao(GroupChats.class, groupChatsDao);
        registerDao(SelectedId.class, selectedIdDao);
        registerDao(SystemMsg.class, systemMsgDao);
        registerDao(MsgHistory.class, msgHistoryDao);
        registerDao(LocalPhone.class, localPhoneDao);
        registerDao(NotifyList.class, notifyListDao);
        registerDao(FilePicture.class, filePictureDao);
        registerDao(ModuleCount.class, moduleCountDao);
        registerDao(SlowNotifyList.class, slowNotifyListDao);
    }
    
    public void clear() {
        messagesDaoConfig.getIdentityScope().clear();
        parentDeptDaoConfig.getIdentityScope().clear();
        subDeptDaoConfig.getIdentityScope().clear();
        topContactsDaoConfig.getIdentityScope().clear();
        chatListDaoConfig.getIdentityScope().clear();
        groupChatsDaoConfig.getIdentityScope().clear();
        selectedIdDaoConfig.getIdentityScope().clear();
        systemMsgDaoConfig.getIdentityScope().clear();
        msgHistoryDaoConfig.getIdentityScope().clear();
        localPhoneDaoConfig.getIdentityScope().clear();
        notifyListDaoConfig.getIdentityScope().clear();
        filePictureDaoConfig.getIdentityScope().clear();
        moduleCountDaoConfig.getIdentityScope().clear();
        slowNotifyListDaoConfig.getIdentityScope().clear();
    }

    public MessagesDao getMessagesDao() {
        return messagesDao;
    }

    public ParentDeptDao getParentDeptDao() {
        return parentDeptDao;
    }

    public SubDeptDao getSubDeptDao() {
        return subDeptDao;
    }

    public TopContactsDao getTopContactsDao() {
        return topContactsDao;
    }

    public ChatListDao getChatListDao() {
        return chatListDao;
    }

    public GroupChatsDao getGroupChatsDao() {
        return groupChatsDao;
    }

    public SelectedIdDao getSelectedIdDao() {
        return selectedIdDao;
    }

    public SystemMsgDao getSystemMsgDao() {
        return systemMsgDao;
    }

    public MsgHistoryDao getMsgHistoryDao() {
        return msgHistoryDao;
    }

    public LocalPhoneDao getLocalPhoneDao() {
        return localPhoneDao;
    }

    public NotifyListDao getNotifyListDao() {
        return notifyListDao;
    }

    public FilePictureDao getFilePictureDao() {
        return filePictureDao;
    }

    public ModuleCountDao getModuleCountDao() {
        return moduleCountDao;
    }

    public SlowNotifyListDao getSlowNotifyListDao() {
        return slowNotifyListDao;
    }

}
