package com.tky.mqtt.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.tky.mqtt.base.BaseDao;

/**
 * Entity mapped to table LOCAL_PHONE.
 */
public class LocalPhone extends BaseDao {

    private String id;
    private String platformid;
    private String name;
    private String phonenumber;
    private String pinyinname;

    public LocalPhone() {
    }

    public LocalPhone(String id) {
        this.id = id;
    }

    public LocalPhone(String id, String platformid, String name, String phonenumber, String pinyinname) {
        this.id = id;
        this.platformid = platformid;
        this.name = name;
        this.phonenumber = phonenumber;
        this.pinyinname = pinyinname;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPlatformid() {
        return platformid;
    }

    public void setPlatformid(String platformid) {
        this.platformid = platformid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhonenumber() {
        return phonenumber;
    }

    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    public String getPinyinname() {
        return pinyinname;
    }

    public void setPinyinname(String pinyinname) {
        this.pinyinname = pinyinname;
    }

}
