package com.tky.mqtt.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.tky.mqtt.dao.NewNotifyList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table NEW_NOTIFY_LIST.
*/
public class NewNotifyListDao extends AbstractDao<NewNotifyList, String> {

    public static final String TABLENAME = "NEW_NOTIFY_LIST";

    /**
     * Properties of entity NewNotifyList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property MsgId = new Property(0, String.class, "MsgId", true, "MSG_ID");
        public final static Property IsRead = new Property(1, String.class, "isRead", false, "IS_READ");
        public final static Property AppId = new Property(2, String.class, "appId", false, "APP_ID");
        public final static Property AppName = new Property(3, String.class, "appName", false, "APP_NAME");
    };


    public NewNotifyListDao(DaoConfig config) {
        super(config);
    }
    
    public NewNotifyListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'NEW_NOTIFY_LIST' (" + //
                "'MSG_ID' TEXT PRIMARY KEY NOT NULL ," + // 0: MsgId
                "'IS_READ' TEXT," + // 1: isRead
                "'APP_ID' TEXT," + // 2: appId
                "'APP_NAME' TEXT);"); // 3: appName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'NEW_NOTIFY_LIST'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, NewNotifyList entity) {
        stmt.clearBindings();
 
        String MsgId = entity.getMsgId();
        if (MsgId != null) {
            stmt.bindString(1, MsgId);
        }
 
        String isRead = entity.getIsRead();
        if (isRead != null) {
            stmt.bindString(2, isRead);
        }
 
        String appId = entity.getAppId();
        if (appId != null) {
            stmt.bindString(3, appId);
        }
 
        String appName = entity.getAppName();
        if (appName != null) {
            stmt.bindString(4, appName);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public NewNotifyList readEntity(Cursor cursor, int offset) {
        NewNotifyList entity = new NewNotifyList( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // MsgId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // isRead
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // appId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // appName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, NewNotifyList entity, int offset) {
        entity.setMsgId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setIsRead(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAppId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAppName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(NewNotifyList entity, long rowId) {
        return entity.getMsgId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(NewNotifyList entity) {
        if(entity != null) {
            return entity.getMsgId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
