package com.tky.mqtt.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import com.tky.mqtt.base.BaseDao;

/**
 * Entity mapped to table NEW_NOTIFY_LIST.
 */
public class NewNotifyList extends BaseDao {

    private String MsgId;
    private String isRead;
    private String appId;
    private String appName;

    public NewNotifyList() {
    }

    public NewNotifyList(String MsgId) {
        this.MsgId = MsgId;
    }

    public NewNotifyList(String MsgId, String isRead, String appId, String appName) {
        this.MsgId = MsgId;
        this.isRead = isRead;
        this.appId = appId;
        this.appName = appName;
    }

    public String getMsgId() {
        return MsgId;
    }

    public void setMsgId(String MsgId) {
        this.MsgId = MsgId;
    }

    public String getIsRead() {
        return isRead;
    }

    public void setIsRead(String isRead) {
        this.isRead = isRead;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

}
