package com.tky.mqtt.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import com.tky.mqtt.base.BaseDao;

/**
 * Entity mapped to table QYYICON_PATH.
 */
public class QYYIconPath extends BaseDao {

    private String appId;
    private String path;

    public QYYIconPath() {
    }

    public QYYIconPath(String appId) {
        this.appId = appId;
    }

    public QYYIconPath(String appId, String path) {
        this.appId = appId;
        this.path = path;
    }

    public String getAppId() {
        return appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

}
