package com.tky.mqtt.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.tky.mqtt.dao.SelectedId;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SELECTED_ID.
*/
public class SelectedIdDao extends AbstractDao<SelectedId, String> {

    public static final String TABLENAME = "SELECTED_ID";

    /**
     * Properties of entity SelectedId.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Grade = new Property(1, String.class, "grade", false, "GRADE");
        public final static Property Isselected = new Property(2, Boolean.class, "isselected", false, "ISSELECTED");
    };


    public SelectedIdDao(DaoConfig config) {
        super(config);
    }
    
    public SelectedIdDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SELECTED_ID' (" + //
                "'ID' TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "'GRADE' TEXT," + // 1: grade
                "'ISSELECTED' INTEGER);"); // 2: isselected
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SELECTED_ID'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SelectedId entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String grade = entity.getGrade();
        if (grade != null) {
            stmt.bindString(2, grade);
        }
 
        Boolean isselected = entity.getIsselected();
        if (isselected != null) {
            stmt.bindLong(3, isselected ? 1l: 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SelectedId readEntity(Cursor cursor, int offset) {
        SelectedId entity = new SelectedId( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // grade
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0 // isselected
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SelectedId entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setGrade(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIsselected(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(SelectedId entity, long rowId) {
        return entity.getId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(SelectedId entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
