package com.tky.mqtt.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import com.tky.mqtt.base.BaseDao;

/**
 * Entity mapped to table SELECTED_ID.
 */
public class SelectedId extends BaseDao {

    private String id;
    private String grade;
    private Boolean isselected;

    public SelectedId() {
    }

    public SelectedId(String id) {
        this.id = id;
    }

    public SelectedId(String id, String grade, Boolean isselected) {
        this.id = id;
        this.grade = grade;
        this.isselected = isselected;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getGrade() {
        return grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }

    public Boolean getIsselected() {
        return isselected;
    }

    public void setIsselected(Boolean isselected) {
        this.isselected = isselected;
    }

}
