package com.tky.mqtt.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MSG_HISTORY.
 */
public class MsgHistory {

    private String _id;
    private String msg;
    private Long when;
    private String type;

    public MsgHistory() {
    }

    public MsgHistory(String _id) {
        this._id = _id;
    }

    public MsgHistory(String _id, String msg, Long when, String type) {
        this._id = _id;
        this.msg = msg;
        this.when = when;
        this.type = type;
    }

    public String get_id() {
        return _id;
    }

    public void set_id(String _id) {
        this._id = _id;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public Long getWhen() {
        return when;
    }

    public void setWhen(Long when) {
        this.when = when;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
